name: Python Linting

  pull_request:
    branches:
      - main  # or whatever branch you want to trigger this for
  push:
    branches:
      - main  # or any other branch you want to trigger linting on

jobs:
  lint:
    runs-on: ubuntu-latest  # You can choose another OS if needed

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version you want to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from your requirements file

      # Step 4: Install pylint
      - name: Install pylint
        run: pip install pylint

      # Step 5: Run pylint
      - name: Run pylint
        run: |
          pylint **/*.py  # Lint all Python files in the repo
